### ISSUE TITLE
Indexer should include processed Code Ocean results

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/aind-data-asset-indexer#38]
The indexer needs to include assets that are processed results in the Code Ocean datasets bucket. This is needed so that science teams can analyze data as soon as it is processed, regardless of whether we are capturing it to an external bucket.

**Acceptance Criteria**
- [ ] The indexer crawls the Code Ocean datasets bucket.
- [ ] The indexer looks at all top-level prefixes. If the prefix contains (*not* recursively) any of the well-known JSON files (data_description.json, subject.json, procedures.json, rig.json, session.json, instrument.json, acquisition.json), include it in the index.
- [ ] Query Code Ocean to populate relevant Metadata record fields (name, creation time, etc).

**Comment by jtyoung84** [comment]
Dev account bucket: codeocean-s3datasetsbucket-eg0euwi4ez6z
Prod account bucket: codeocean-s3datasetsbucket-1u41qdg42ur9
