### ISSUE TITLE
missing assets from docdb

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/aind-data-asset-indexer#46]
**Describe the bug**
The following prefixes, which all exist in `s3://aind-open-data`, are not showing up in the docdb and therefore not showing on the SmartSPIM dashboard.

- SmartSPIM_705130_2024-02-14_14-07-29_stitched_2024-02-15_21-47-28
- SmartSPIM_705129_2024-02-14_10-39-43_stitched_2024-02-15_20-58-26
- SmartSPIM_717200_2024-04-23_22-21-26_stitched_2024-04-25_00-39-12
- SmartSPIM_716949_2024-04-23_12-53-35_stitched_2024-04-24_15-46-00
- SmartSPIM_716950_2024-04-23_17-36-59_stitched_2024-04-24_22-47-42

**Comment by dyf** [comment]
Update: 705130 and 705129 are missing records in Code Ocean, which I will create now. The other three have normal looking CO records.

**Comment by dyf** [comment]
I have created records for those two.

**Comment by jtyoung84** [comment]
Code Ocean changed their response, which caused external assets to be filtered from the data asset indexer. Should be resolved via this commit: [b6397a6](https://github.com/AllenNeuralDynamics/aind-data-asset-indexer/commit/b6397a6803ee6931bd7bc151907a205969738c44)
