### ISSUE TITLE
Add better logging to output

### ISSUE THREAD

**Issue by jtyoung84** [AllenNeuralDynamics/aind-data-asset-indexer#5]
# User story
As a user, I want to have logging, so I can have better insight in case something goes wrong.

# Acceptance criteria
- [ ] Use logging library
- [ ] Define log level as env var
- [ ] Add some useful logging statements about the status of the job

# Sprint Ready Checklist 
- [ ] 1. Acceptance criteria defined 
- [ ] 2. Team understands acceptance criteria 
- [ ] 3. Team has defined solution / steps to satisfy acceptance criteria 
- [ ] 4. Acceptance criteria is verifiable / testable 
- [ ] 5. External / 3rd Party dependencies identified
- [ ] 6. Ticket is prioritized and sized

# Notes
*Add any helpful notes here.*

**Comment by dyf** [comment]
not needed, different indexer is running
