### ISSUE TITLE
Pull code ocean api token from aws secrets manager

### ISSUE THREAD

**Issue by jtyoung84** [AllenNeuralDynamics/aind-data-asset-indexer#7]
# User story
As a developer, I want to pull the code ocean token from aws secrets manager, so I can avoid forgetting to update it if it rolls over.

# Acceptance criteria
- [ ] The codeocean-api-token is pulled from service instead of included as an env variable.

# Sprint Ready Checklist 
- [ ] 1. Acceptance criteria defined 
- [ ] 2. Team understands acceptance criteria 
- [ ] 3. Team has defined solution / steps to satisfy acceptance criteria 
- [ ] 4. Acceptance criteria is verifiable / testable 
- [ ] 5. External / 3rd Party dependencies identified
- [ ] 6. Ticket is prioritized and sized

# Notes
*Add any helpful notes here.*

**Comment by dyf** [comment]
closing, old indexer
