### ISSUE TITLE
Adjust `external_links` input expectations

### ISSUE THREAD

**Issue by Sun-flow** [AllenNeuralDynamics/aind-data-asset-indexer#74]
Aind Data Schema recently had changes which converted `Metadata.external_links` from being a List of Dicts to a Dict of Lists. This is a breaking change, which needs to be updated in the indexer. 

Indexer will need to sort external links in the new format `Dict[ExternalPlatform, List[str]]`

**Comment by helen-m-lin** [comment]
This is where the indexer code needs to be updated for enabling the format change for future records:
https://github.com/AllenNeuralDynamics/aind-data-asset-indexer/blob/f6cacb0a061d0cbab6de9fafc4bb28eb87809406/src/aind_data_asset_indexer/utils.py#L1020

**Comment by jtyoung84** [comment]
We should wait until aind-data-schema v1.0 is rolled out
